version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s [%(levelname)s] %(message)s'
    datefmt: '%m/%d/%Y %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: error.log
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: utf8
loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console, info_file, error_file]
